package com.springboot.demo.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "This entity contains Movie details")
@Entity
@Table(name = "movie_details")
public class Movie {
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@ApiModelProperty(notes = "This is a autogenerated id", required = true, position = 1)
	private int mId;
	@Column(name = "name")
	@Size(max = 10,min = 2,message = "Movie name must be 2-10 characters")
	@ApiModelProperty(notes = "This is Movie name", example = "KGF", required = true, position = 1)
	private String mName;
	@Column(name = "director")
	@ApiModelProperty(notes = "This is Director Name", example = "Anirban Das", required = true, position = 1)
	private String mDirector;
	public Movie() {
		super();
	}
	public Movie(int mId, String mName, String mDirector) {
		super();
		this.mId = mId;
		this.mName = mName;
		this.mDirector = mDirector;
	}
	public int getmId() {
		return mId;
	}
	public void setmId(int mId) {
		this.mId = mId;
	}
	public String getmName() {
		return mName;
	}
	public void setmName(String mName) {
		this.mName = mName;
	}
	public String getmDirector() {
		return mDirector;
	}
	public void setmDirector(String mDirector) {
		this.mDirector = mDirector;
	}
	@Override
	public String toString() {
		return "Movie [mId=" + mId + ", mName=" + mName + ", mDirector=" + mDirector + "]";
	}
	
}
